import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Lang = 'pt' | 'en' | 'es';

const currencyByLang: Record<Lang, string> = {
  pt: 'R$',
  en: 'US$',
  es: '$',
};

const translations: Record<string, Record<Lang, string>> = {
  hello: { pt: 'Olá', en: 'Hello', es: 'Hola' },
  user: { pt: 'Usuário', en: 'User', es: 'Usuario' },
  home: { pt: 'Início', en: 'Home', es: 'Inicio' },
  lists: { pt: 'Listas', en: 'Lists', es: 'Listas' },
  stock: { pt: 'Estoque', en: 'Stock', es: 'Stock' },
  savings: { pt: 'Economizar', en: 'Savings', es: 'Ahorros' },
  history: { pt: 'Histórico', en: 'History', es: 'Historial' },
  reset: { pt: 'Resetar Filtrar', en: 'Reset Filter', es: 'Restablecer Filtro' },
  reports: { pt: 'Relatórios', en: 'Reports', es: 'Informes' },
  scanner: { pt: 'Scanner', en: 'Scanner', es: 'Escáner' },
  themes: { pt: 'Temas', en: 'Themes', es: 'Temas' },
  languages: { pt: 'Idiomas', en: 'Languages', es: 'Idiomas' },
  preferences: { pt: 'Preferências', en: 'Preferences', es: 'Preferencias' },
  about: { pt: 'Sobre', en: 'About', es: 'Acerca de' },
  accountDeleted: { pt: 'Conta excluída.', en: 'Account deleted.', es: 'Cuenta eliminada.' },
  confirmLogout: { pt: 'Deseja realmente sair?', en: 'Do you really want to log out?', es: '¿Realmente quieres salir?' },
  logout: { pt: 'Sair', en: 'Logout', es: 'Salir' },
  resetAll: { pt: 'Reset Geral', en: 'Reset All', es: 'Restablecer Todo' },
  deleteAccount: { pt: 'Excluir Conta', en: 'Delete Account', es: 'Eliminar Cuenta' },
  confirmDeletePurchaseTitle: { pt: 'Excluir Compra', en: 'Delete Purchase', es: 'Eliminar Compra' },
  confirmDeletePurchaseDesc: { pt: 'Deseja realmente excluir todos os itens desta compra? Esta ação não pode ser desfeita.', en: 'Do you really want to delete all items from this purchase? This action cannot be undone.', es: '¿Realmente deseas eliminar todos los ítems de esta compra? Esta acción no se puede deshacer.' },
  purchaseDeleted: { pt: 'Compra excluída com sucesso.', en: 'Purchase successfully deleted.', es: 'Compra eliminada con éxito.' },
  light: { pt: 'Claro', en: 'Light', es: 'Claro' },
  dark: { pt: 'Escuro', en: 'Dark', es: 'Oscuro' },
  largeText: { pt: 'Letras Grandes', en: 'Large Text', es: 'Texto Grande' },
  themeDesc: { pt: 'Aparência do aplicativo', en: 'App appearance', es: 'Apariencia de la app' },
  langDesc: { pt: 'Escolher idioma do app', en: 'Choose app language', es: 'Elegir idioma' },
  prefDesc: { pt: 'Ajustes gerais', en: 'General settings', es: 'Ajustes generales' },
  aboutDesc: { pt: 'Informações do aplicativo', en: 'App information', es: 'Información de la app' },
  logoutDesc: { pt: 'Fazer logout da conta', en: 'Log out of account', es: 'Cerrar sesión' },
  resetDesc: { pt: 'Apagar todos as listas, histórico e estoques', en: 'Delete all lists, history and stock', es: 'Borrar listas, historial y stock' },
  deleteDesc: { pt: 'Apaga permanentemente a conta', en: 'Permanently delete account', es: 'Eliminar cuenta permanentemente' },
  stockExpiry: { pt: 'Dias para excluir item do estoque', en: 'Days to delete stock item', es: 'Días para eliminar del stock' },
  days: { pt: 'dias', en: 'days', es: 'días' },
  developedBy: { pt: 'Desenvolvido por ID Apps 2026', en: 'Developed by ID Apps 2026', es: 'Desarrollado por ID Apps 2026' },
  termsText: { pt: 'Ao usar este app você aceita os termos de uso e privacidade em:', en: 'By using this app you accept the terms of use and privacy at:', es: 'Al usar esta app aceptas los términos de uso y privacidad en:' },
  login: { pt: 'Entrar', en: 'Sign In', es: 'Iniciar Sesión' },
  loginToSubscribe: { pt: 'Entrar para Assinar', en: 'Sign in to Subscribe', es: 'Iniciar sesión para Suscribirse' },
  loginWithGoogle: { pt: 'Entrar com Google', en: 'Sign in with Google', es: 'Iniciar con Google' },
  loginWithDifferentAccount: { pt: 'Entrar com uma conta diferente', en: 'Sign in with a different account', es: 'Iniciar con una cuenta diferente' },
  sessionMoved: { pt: 'Sua conta foi conectada em outro aparelho. Desconectando...', en: 'Your account was connected on another device. Signing out...', es: 'Su conta ha sido conectada en otro dispositivo. Cerrando sesión...' },
  loginWithEmail: { pt: 'Entrar com E-mail', en: 'Sign in with Email', es: 'Iniciar con E-mail' },
  loginSuccess: { pt: 'Login realizado com sucesso!', en: 'Login successful!', es: '¡Inicio de sesión exitoso!' },
  email: { pt: 'E-mail', en: 'Email', es: 'Correo' },
  password: { pt: 'Senha', en: 'Password', es: 'Contraseña' },
  signUp: { pt: 'Criar conta', en: 'Sign Up', es: 'Criar cuenta' },
  noAccount: { pt: 'Não tem conta?', en: "Don't have an account?", es: '¿No tienes cuenta?' },
  hasAccount: { pt: 'Já tem conta?', en: 'Already have an account?', es: '¿Ya tienes cuenta?' },
  checkingSubscription: { pt: 'Verificando assinatura...', en: 'Checking subscription...', es: 'Verificando suscripción...' },
  restorePurchase: { pt: 'Restaurar Assinatura', en: 'Restore Subscription', es: 'Restaurar Suscripción' },
  devMode: { pt: 'Modo Desenvolvedor (Bypass)', en: 'Developer Mode (Bypass)', es: 'Modo de Desarrollador (Bypass)' },
  restoreDesc: { pt: 'Restaurar compras anteriores', en: 'Restore previous purchases', es: 'Restaurar compras anteriores' },
  manageSubscription: { pt: 'Gerenciar Assinatura', en: 'Manage Subscription', es: 'Gestionar Suscripción' },
  manageSubDesc: { pt: 'Acesse a Central do Cliente', en: 'Access Customer Center', es: 'Acceder al Centro de Clientes' },
  welcomeBack: { pt: 'Bem-vindo de volta!', en: 'Welcome back!', es: '¡Bienvenido de nuevo!' },
  locationPermissionTitle: { pt: 'Uso de Localização', en: 'Location Usage', es: 'Uso de Ubicación' },
  locationPermissionDesc: { pt: 'A Magic Mart solicita sua localização para sugerir automaticamente o nome do mercado onde você está.', en: 'Magic Mart requests your location to automatically suggest the name of the market where you are.', es: 'Magic Mart solicita su ubicación para sugerir automáticamente el nombre del mercado donde se encuentra.' },
  cameraPermissionTitle: { pt: 'Uso da Câmera', en: 'Camera Usage', es: 'Uso de Cámara' },
  cameraPermissionDesc: { pt: 'A Magic Mart solicita acesso à câmera para que a IA identifique produtos automaticamente.', en: 'Magic Mart requests camera access so the AI can automatically identify products.', es: 'Magic Mart solicita acceso a la cámara para que la IA identifique productos automáticamente.' },
  allow: { pt: 'Permitir', en: 'Allow', es: 'Permitir' },
  notNow: { pt: 'Agora não', en: 'Not now', es: 'Ahora no' },
  confirmReset: { pt: 'Tem certeza? Isso apagará todas as listas, histórico e estoque.', en: 'Are you sure? This will delete all lists, history and stock.', es: '¿Estás seguro? Esto eliminará listas, historial y stock.' },
  tip: { pt: 'Dica', en: 'Tip', es: 'Tip' },
  confirmDelete: { pt: 'Tem certeza? Sua conta será apagada permanentemente.', en: 'Are you sure? Your account will be permanently deleted.', es: '¿Estás seguro? Tu cuenta será eliminada permanentemente.' },
  confirm: { pt: 'Confirmar', en: 'Confirm', es: 'Confirmar' },
  cancel: { pt: 'Cancelar', en: 'Cancel', es: 'Cancelar' },
  newList: { pt: 'Listas de Compras', en: 'Shopping Lists', es: 'Listas de Compras' },
  finishList: { pt: 'Concluir Lista', en: 'Finish List', es: 'Finalizar Lista' },
  saveList: { pt: 'Salvar Lista', en: 'Save List', es: 'Guardar Lista' },
  editList: { pt: 'Editar Lista', en: 'Edit List', es: 'Editar Lista' },
  endShopping: { pt: 'Encerrar Compras', en: 'End Shopping', es: 'Terminar Compras' },
  endShoppingBanner: { pt: 'Ao encerrar, os itens vão apenas para o histórico. O estoque será atualizado após você escanear o cupom fiscal.', en: 'When finishing, items only go to history. Stock will be updated after you scan the receipt.', es: 'Al finalizar, los artículos solo van al historial. El stock se atualizará después de escanear el recibo.' },
  createList: { pt: 'Gerenciar e criar listas', en: 'Manage and create lists', es: 'Gestionar y crear listas' },
  goShopping: { pt: 'Fazer Mercado', en: 'Go Shopping', es: 'Ir al Mercado' },
  addProducts: { pt: 'Adicionar produtos na cesta', en: 'Add products to basket', es: 'Agregar produtos' },
  scan: { pt: 'Escanear', en: 'Scan', es: 'Escanear' },
  receipt: { pt: 'Nota fiscal', en: 'Receipt', es: 'Recibo' },
  share: { pt: 'Compartilhar', en: 'Share', es: 'Compartir' },
  shopping: { pt: 'Fazer Mercado', en: 'Shopping', es: 'Ir al mercado' },
  shareSubtitle: { pt: 'Selecione as listas para compartilhar', en: 'Select lists to share', es: 'Selecciona listas para compartir' },
  activeLists: { pt: 'Enviar Listas de Compras', en: 'Send Shopping Lists', es: 'Enviar Listas de Compras' },
  activeListsTitle: { pt: 'Listas Ativas', en: 'Active Lists', es: 'Listas Activas' },
  confirmRestore: { pt: 'Tem certeza? Isso substituirá todos os dados atuais (estoque, histórico e listas) pelos dados do backup.', en: 'Are you sure? This will replace all current data (stock, history and lists) with the backup data.', es: '¿Estás seguro? Esto reemplazará todos los datos actuales (stock, historial y listas) con los datos del respaldo.' },
  noResults: { pt: 'Nenhum resultado encontrado', en: 'No results found', es: 'No se encontraron resultados' },
  cheapDays: { pt: 'Dias de compras mais baratos', en: 'Cheapest shopping days', es: 'Días de compras más baratos' },
  alerts: { pt: 'Alertas', en: 'Alerts', es: 'Alertas' },
  item: { pt: 'item', en: 'item', es: 'ítem' },
  items: { pt: 'Itens', en: 'Items', es: 'Ítems' },
  analysisError: { pt: 'Erro na análise. Verifique sua chave API ou conexão.', en: 'Analysis error. Check your API key or connection.', es: 'Error en el análisis. Revisa tu clave API o conexión.' },
  recognitionCanceled: { pt: 'Reconhecimento cancelado.', en: 'Recognition canceled.', es: 'Reconocimiento cancelado.' },
  productRecognized: { pt: 'Produto reconhecido: {name}', en: 'Product recognized: {name}', es: 'Producto reconocido: {name}' },
  active: { pt: 'Ativas', en: 'Active', es: 'Activas' },
  currentMonth: { pt: 'Mês Atual', en: 'Current Month', es: 'Mes Actual' },
  daysLeft: { pt: 'dias restantes', en: 'days left', es: 'días restantes' },
  noActiveLists: { pt: 'Nenhuma lista ativa', en: 'No active lists', es: 'Sin listas activas' },
  stockUpToDate: { pt: 'Estoque em dia ✅', en: 'Stock up to date ✅', es: 'Stock al día ✅' },
  clear: { pt: 'Limpar', en: 'Clear', es: 'Limpiar' },
  seeAll: { pt: 'Ver todas', en: 'See all', es: 'Ver todas' },
  menu: { pt: 'Menu', en: 'Menu', es: 'Menú' },
  geminiApiKey: { pt: 'Chave API Gemini', en: 'Gemini API Key', es: 'Clave API Gemini' },
  geminiApiKeyDesc: { pt: 'Chave pessoal para funções de IA', en: 'Personal key for AI features', es: 'Clave personal for funciones de IA' },
  geminiApiKeySaved: { pt: 'Chave salva com sucesso!', en: 'Key saved successfully!', es: '¡Clave guardada!' },
  geminiApiKeyDeleted: { pt: 'Chave removida.', en: 'Key removed.', es: 'Clave eliminada.' },
  geminiPaste: { pt: 'Colar', en: 'Paste', es: 'Pegar' },
  geminiDelete: { pt: 'Apagar', en: 'Delete', es: 'Borrar' },
  geminiSave: { pt: 'Salvar', en: 'Save', es: 'Guardar' },
  geminiPlaceholder: { pt: 'Cole sua chave API aqui', en: 'Paste your API key here', es: 'Pegue su clave API aquí' },
  geminiConfigured: { pt: 'Configurada', en: 'Configured', es: 'Configurada' },
  geminiNotConfigured: { pt: 'Não configurada', en: 'Not configured', es: 'No configurada' },
  geminiHelpTitle: { pt: 'Como obter sua chave API Gemini', en: 'How to get your Gemini API Key', es: 'Cómo obtener tu clave API Gemini' },
  geminiHelpSteps: {
    pt: '1. Acesse https://aistudio.google.com/apikey\n2. Faça login com sua conta Google\n3. Clique em "Create API Key"\n4. Copie a chave gerada\n5. Cole aqui no app e salve',
    en: '1. Go to https://aistudio.google.com/apikey\n2. Sign in with your Google account\n3. Click "Create API Key"\n4. Copy the generated key\n5. Paste it here in the app and save',
    es: '1. Accede a aistudio.google.com\n2. Inicia sesión con tu cuenta Google\n3. Haz clic en "Get API Key" en el menú\n4. Haz clic em "Create API Key"\n5. Copia la clave generada\n6. Pégala aquí en la app y guarda',
  },
  enterApiKeyBeforeTest: { pt: 'Insira a chave API antes de testar', en: 'Enter API key before testing', es: 'Ingresa la clave API antes de probar' },
  testingIAConnection: { pt: 'Testando conexão com a IA...', en: 'Testing AI connection...', es: 'Probando conexión con a IA...' },
  testPrompt: { pt: 'Responda apenas com a palavra OK se você estiver funcionando corretamente.', en: 'Respond only with the word OK if you are working correctly.', es: 'Responde solo com la palabra OK si estás funcionando correctamente.' },
  iaConnectionSuccess: { pt: 'Conexão bem-sucedida!', en: 'Connection successful!', es: '¡Conexión exitosa!' },
  iaUnexpectedResponse: { pt: 'Resposta inesperada da IA:', en: 'Unexpected AI response:', es: 'Respuesta inesperada de la IA:' },
  connectionError: { pt: 'Erro de conexão:', en: 'Connection error:', es: 'Error de conexión:' },
  unknownError: { pt: 'Erro desconhecido', en: 'Unknown error', es: 'Error desconocido' },
  profileDataTitle: { pt: 'Dados do perfil:', en: 'Profile data:', es: 'Dados do perfil:' },
  profileDataNotLoaded: { pt: 'Dados do perfil não carregados.', en: 'Profile data not loaded.', es: 'Dados do perfil não carregados.' },
  aiDiagnosis: { pt: 'Diagnóstico da IA', en: 'AI Diagnosis', es: 'Diagnóstico de la IA' },
  testIAConnection: { pt: 'Testar Conexão', en: 'Test Connection', es: 'Probar Conexión' },
  viewProfileData: { pt: 'Ver Meus Dados', en: 'View My Data', es: 'Ver Mis Dados' },
  scannerApiKeyInfo: {
    pt: 'Para escanear cupons, configure sua chave API Gemini no menu de configurações.',
    en: 'To scan receipts, set up your Gemini API key in the settings menu.',
    es: 'Para escanear recibos, configura tu clave API Gemini en el menú de ajustes.',
  },
  scannerApiKeyConfigured: {
    pt: 'Chave API Gemini configurada. Para trocar a chave, acesse o menu de configurações.',
    en: 'Gemini API key configured. To change it, go to the settings menu.',
    es: 'Clave API Gemini configurada. Para cambiarla, accede al menú de ajustes.',
  },
  scannerGoToSettings: {
    pt: 'Abrir Configurações',
    en: 'Open Settings',
    es: 'Abrir Ajustes',
  },
  addStockItem: { pt: 'Adicionar Produto', en: 'Add Product', es: 'Agregar Producto' },
  scanReceiptBtn: { pt: 'Scanner Cupom', en: 'Receipt Scanner', es: 'Escáner de Recibo' },
  anytime: { pt: 'Qualquer data', en: 'Any date', es: 'Cualquer fecha' },
  allStores: { pt: 'Todas as lojas', en: 'All stores', es: 'Todas las tiendas' },
  back: { pt: 'Voltar', en: 'Back', es: 'Volver' },
  save: { pt: 'Salvar', en: 'Save', es: 'Guardar' },
  cancelBtn: { pt: 'Cancelar', en: 'Cancel', es: 'Cancelar' },
  analyzingWithAI: { pt: 'Analisando com IA...', en: 'Analyzing with AI...', es: 'Analizando con IA...' },
  completedPercent: { pt: 'concluído', en: 'completed', es: 'completado' },
  optimizeImages: { pt: 'Otimizando imagens...', en: 'Optimizing images...', es: 'Optimizando imágenes...' },
  sendingImages: { pt: 'Enviando imagens para análise...', en: 'Sending images for analysis...', es: 'Enviando imágenes para análise...' },
  processingResponse: { pt: 'Resposta recebida. Processando itens...', en: 'Response received. Processing items...', es: 'Respuesta recibida. Procesando ítems...' },
  completingAnalysis: { pt: 'Concluído!', en: 'Done!', es: '¡Completado!' },
  missingApiKeyError: { pt: 'Chave API não encontrada. Por favor, configure-a no Menu > Configurações.', en: 'API Key not found. Please configure it in Menu > Settings.', es: 'Clave API não encontrada. Por favor, configúrala en el Menú > Ajustes.' },
  singlePhoto: { pt: 'Foto Única', en: 'Single Photo', es: 'Foto Única' },
  singlePhotoDesc: { pt: 'Para cupons pequenos que cabem em uma única foto', en: 'For small receipts that fit in a single photo', es: 'Para cupones pequeños que caben en una sola foto' },
  multiPhoto: { pt: 'Múltiplas Fotos', en: 'Multiple Photos', es: 'Múltiples Fotos' },
  multiPhotoDesc: { pt: 'Para cupons longos — tire várias fotos e a IA consolida tudo', en: 'For long receipts — take several photos and AI consolidates it all', es: 'Para cupones largos — toma varias fotos y la IA consolida todo' },
  scannerHistory: { pt: 'Histórico de Cupons', en: 'Receipt History', es: 'Historial de Cupones' },
  scannerHistoryDesc: { pt: 'Veja todos os cupons escaneados e gerencie seus registros', en: 'See all scanned receipts and manage your records', es: 'Ver todos los cupones escaneados' },
  aiScannerTitle: { pt: 'Scanner com Inteligência Artificial', en: 'AI-Powered Scanner', es: 'Escáner con Inteligencia Artificial' },
  aiScannerDesc: { pt: 'O escâner utiliza IA para detectar e extrair texto dos cupons fiscais automaticamente. Para funcionar, é necessária uma chave API do Gemini, que pode ser obtida gratuitamente.', en: 'The scanner uses AI to detect and extract text from receipts automatically. To work, a Gemini API key is required, which can be obtained for free.', es: 'El escáner utiliza IA para detectar y extraer texto automáticamente. Se requiere una clave API de Gemini.' },
  getApiKeyHowTo: { pt: 'Como obter sua chave API gratuita:', en: 'How to get your free API key:', es: 'Cómo obtener tu clave API gratuita:' },
  loginToGoogle: { pt: 'Faça login com sua conta Google', en: 'Log in with your Google account', es: 'Inicia sesión con tu cuenta de Google' },
  clickCreateKey: { pt: 'Clique em "Create API Key"', en: 'Click "Create API Key"', es: 'Haz clic en "Create API Key"' },
  copyKey: { pt: 'Copie a chave gerada', en: 'Copy the generated key', es: 'Copia la clave generada' },
  pasteInSettings: { pt: 'Cole a chave em:', en: 'Paste the key in:', es: 'Pegue la clave en:' },
  sumOriginal: { pt: 'Soma dos itens (original)', en: 'Sum of items (original)', es: 'Suma de ítems (original)' },
  discountApplied: { pt: 'Desconto aplicado', en: 'Discount applied', es: 'Descuento aplicado' },
  sumWithDiscount: { pt: 'Soma com desconto', en: 'Sum with discount', es: 'Suma con descuento' },
  receiptTotalKey: { pt: 'Total do cupom', en: 'Receipt total', es: 'Total del cupón' },
  saveToStock: { pt: 'Salvar no Estoque e Histórico', en: 'Save to Stock and History', es: 'Guardar en Stock e Historial' },
  saveToHistoryOnly: { pt: 'Salvar no Histórico', en: 'Save to History', es: 'Guardar en el Historial' },
  applyDiscounts: { pt: 'Aplicar descontos', en: 'Apply discounts', es: 'Aplicar descuentos' },
  withoutDiscounts: { pt: 'Sem descontos', en: 'Without discounts', es: 'Sin descuentos' },
  deleteReceiptConfirm: { pt: 'Excluir cupom?', en: 'Delete receipt?', es: '¿Eliminar cupón?' },
  deleteReceiptDesc: { pt: 'Todos os itens deste cupom serão removidos do histórico e do estoque. Esta ação não pode ser desfeita.', en: 'All items from this receipt will be removed from history and stock. This cannot be undone.', es: 'Todos los ítems se eliminarán del historial y stock. No se puede deshacer.' },
  yesDelete: { pt: 'Sim, excluir', en: 'Yes, delete', es: 'Sí, eliminar' },
  no: { pt: 'Não', en: 'No', es: 'No' },
  scannedReceiptsLabel: { pt: 'cupons escaneados', en: 'scanned receipts', es: 'cupones escaneados' },
  cheaperLabel: { pt: 'mais barata', en: 'cheaper', es: 'más barata' },
  expensiveLabel: { pt: 'mais cara', en: 'more expensive', es: 'más cara' },
  thanPrevious: { pt: 'que as anteriores', en: 'than previous ones', es: 'que las anteriores' },
  thisPurchaseWas: { pt: 'Esta compra saiu', en: 'This purchase was', es: 'Esta compra fue' },
  selectMonth: { pt: 'Selecionar Mês', en: 'Select Month', es: 'Seleccionar Mes' },
  allMonths: { pt: 'Todos os meses', en: 'All months', es: 'Todos los meses' },
  all: { pt: 'Tudo', en: 'All', es: 'Todo' },
  search: { pt: 'Buscar', en: 'Search', es: 'Buscar' },
  product: { pt: 'Produto', en: 'Product', es: 'Producto' },
  noReceiptsScanned: { pt: 'Nenhum cupom escaneado ainda.', en: 'No receipts scanned yet.', es: 'Ningún cupón escaneado aún.' },
  seeItems: { pt: 'Ver itens', en: 'See items', es: 'Ver ítems' },
  delete: { pt: 'Excluir', en: 'Delete', es: 'Eliminar' },
  results: { pt: 'Resultado', en: 'Result', es: 'Resultado' },
  dateNotFound: { pt: 'Data não encontrada', en: 'Date not found', es: 'Fecha no encontrada' },
  extractedFromReceipt: { pt: 'Extraída do cupom', en: 'Extracted from receipt', es: 'Extraída del cupón' },
  fillDateWarning: { pt: 'Preencha a data da compra antes de salvar.', en: 'Fill in the purchase date before saving.', es: 'Completa la fecha de compra antes de guardar.' },
  differenceWarningPrefix: { pt: 'Diferença de', en: 'Difference of', es: 'Diferencia de' },
  differenceWarningSuffix: { pt: 'entre o total do cupom e a soma dos itens. Algum item pode não ter sido identificado corretamente. Ajuste preços, quantidades, ou adicione/remova itens abaixo.', en: 'between the receipt total and the sum of items. Some items may not have been identified correctly. Adjust prices, quantities, or add/remove items below.', es: 'entre el total del cupón y la suma de ítems. Revisa los precios y cantidades.' },
  foundItemsSubtitle: { pt: 'itens encontrados', en: 'items found', es: 'ítems encontrados' },
  addItemBtn: { pt: 'Adicionar Item', en: 'Add Item', es: 'Añadir Ítem' },
  aiStep1: { pt: 'Checando comunicação com servidor', en: 'Checking server communication', es: 'Comprobando comunicación con el servidor' },
  aiStep2: { pt: 'Validando chave API', en: 'Validating API key', es: 'Validando clave API' },
  aiStep3: { pt: 'Comprimindo e enviando foto', en: 'Compressing and sending photo', es: 'Comprimiendo y enviando foto' },
  aiStep4: { pt: 'Localizando local de compra', en: 'Locating purchase location', es: 'Localizando el lugar de compra' },
  aiStep5: { pt: 'Identificando a data', en: 'Identifying the date', es: 'Identificando la fecha' },
  aiStep6: { pt: 'Extraindo itens comprados, quantidades e preços', en: 'Extracting items, quantities and prices', es: 'Extrayendo ítems, cantidades y precios' },
  aiStep7: { pt: 'Consolidando valores', en: 'Consolidating values', es: 'Consolidando valores' },
  today: { pt: 'Data de hoje', en: 'Today', es: 'Hoy' },
  receiptDate: { pt: 'Data do cupom', en: 'Receipt date', es: 'Fecha del cupón' },
  itemsCount: { pt: 'Total de itens no cupom', en: 'Total items on receipt', es: 'Total de ítems en el cupón' },
  noExpensesYet: { pt: 'Ainda não há gastos nesta categoria.', en: 'No expenses yet in this category.', es: 'Aún no hay gastos en esta categoría.' },
  retryAnalysis: { pt: 'Tentar análise novamente', en: 'Retry analysis', es: 'Reintentar análise' },
  aiLimitReached: { pt: 'Notamos que houve um problema com a chave API ou o limite diário de análise da IA foi atingido. Este limite se renova no dia seguinte.', en: 'We noticed a problem with the API key or the daily AI analysis limit has been reached. This limit resets tomorrow.', es: 'Notamos un problema con la clave API o se alcanzó el límite diario de análisis de IA. Este límite se renueva mañana.' },
  addItem: { pt: 'Incluir', en: 'Include', es: 'Incluir' },
  noneFoundMsg: { pt: 'Nenhum item encontrado no cupom.', en: 'No items found on the receipt.', es: 'No se encontraron ítems en el cupón.' },
  lightingTip: { pt: 'Tente fotografar com melhor iluminação.', en: 'Try taking the photo with better lighting.', es: 'Prueba con mejor iluminación.' },
  saveSuccessful: { pt: 'Salvo com sucesso!', en: 'Saved successfully!', es: '¡Guardado con éxito!' },
  itemsAddedMsg: { pt: 'itens adicionados ao estoque e histórico', en: 'items added to stock and history', es: 'ítems añadidos al stock e historial' },
  itemsAddedHistoryOnlyMsg: { pt: 'itens adicionados ao histórico', en: 'items added to history', es: 'ítems añadidos al historial' },
  scanAnotherBtn: { pt: 'Escanear outro cupom', en: 'Scan another receipt', es: 'Escanear otro cupón' },
  takeReceiptPhoto: { pt: 'Tirar Foto do Cupom', en: 'Take Receipt Photo', es: 'Tomar Foto del Cupón' },
  addMorePhotos: { pt: 'Adicionar Mais Fotos', en: 'Add More Photos', es: 'Añadir Mais Fotos' },
  tapToTakePhoto: { pt: 'Toque para tirar foto', en: 'Tap to take photo', es: 'Toca para tomar foto' },
  selectFromGallery: { pt: 'Selecionar da galeria', en: 'Select from gallery', es: 'Selecionar de la galería' },
  multiPhotoTipTitle: { pt: '📸 Cupons longos:', en: '📸 Long receipts:', es: '📸 Cupones largos:' },
  multiPhotoTipDesc: { pt: 'Ao fotografar, garanta que o último item visível de uma foto apareça também no início da próxima foto. Essa sobreposição permite que a IA identifique a junção e evite duplicar itens.', en: 'When photographing, ensure the last visible item of a photo also appears at the beginning of the next photo. This overlap allows AI to identify the junction and avoid duplicating items.', es: 'Al fotografiar, asegúrate de que el último ítem visible aparezca al inicio de la siguiente foto.' },
  imagesAddedMsg: { pt: 'fotos adicionadas — a IA vai identificar as sobreposições automaticamente.', en: 'photos added — AI will identify overlaps automatically.', es: 'fotos añadidas — la IA identificará las superposiciones automáticamente.' },
  processMultiWithAI: { pt: 'Processar fotos com IA', en: 'Process photos with AI', es: 'Procesar fotos con IA' },
  takePhotoSub: { pt: 'Tire uma foto do cupom', en: 'Take a photo of the receipt', es: 'Toma una foto del cupón' },
  photosAddedSub: { pt: 'foto(s) adicionada(s)', en: 'photo(s) added', es: 'foto(s) añadida(s)' },
  historyItemsCount: { pt: 'itens', en: 'items', es: 'ítems' },
  historyItemCount: { pt: 'item', en: 'item', es: 'ítem' },
  purchaseDateLabel: { pt: '📅 Data da compra:', en: '📅 Purchase date:', es: '📅 Fecha de compra:' },
  editItemBtn: { pt: 'OK', en: 'OK', es: 'OK' },
  editProduct: { pt: 'Editar Produto', en: 'Edit Product', es: 'Editar Producto' },
  receiptSaveError: { pt: 'Erro ao salvar o recibo.', en: 'Error saving receipt.', es: 'Error al guardar el recibo.' },
  qtyLabel: { pt: 'Qtd', en: 'Qty', es: 'Cant' },
  unitLabel: { pt: 'Un', en: 'Unit', es: 'Un' },
  unitPriceLabel: { pt: 'Preço un.', en: 'Unit price', es: 'Precio un.' },
  discountLabel: { pt: 'Desconto', en: 'Discount', es: 'Descuento' },
  originalLabel: { pt: 'Original', en: 'Original', es: 'Original' },
  withDiscountLabel: { pt: 'Com desconto', en: 'With discount', es: 'Con descuento' },
  historySubtitle: { pt: 'Suas compras anteriores', en: 'Your previous purchases', es: 'Tus compras anteriores' },
  monthTotal: { pt: 'Total do mês', en: 'Month total', es: 'Total del mes' },
  editAddressTitle: { pt: 'Editar Endereço', en: 'Edit Address', es: 'Editar Dirección' },
  locationLabel: { pt: 'Local', en: 'Location', es: 'Ubicación' },
  scanReceiptMsg: { pt: 'Escaneie o cupom fiscal desta compra para completar informações faltantes', en: 'Scan the receipt for this purchase to complete missing info', es: 'Escanea el recibo de esta compra para completar información' },
  editBtn: { pt: 'Editar', en: 'Edit', es: 'Editar' },
  invalidDate: { pt: 'Data Inválida', en: 'Invalid Date', es: 'Fecha Inválida' },
  gettingLocation: { pt: 'Obtendo localização...', en: 'Getting location...', es: 'Obteniendo ubicación...' },
  reminderListName: { pt: 'Lembrete de Compras', en: 'Shopping Reminders', es: 'Recordatorios de Compra' },
  addedToReminders: { pt: 'adicionado à lista Lembrete de Compras', en: 'added to Shopping Reminders', es: 'agregado a Recordatorios de Compra' },
  stockText: { pt: 'Estoque', en: 'Stock', es: 'Stock' },
  productName: { pt: 'Nome do produto', en: 'Product name', es: 'Nombre del producto' },
  productNamePlaceholder: { pt: 'Ex: Arroz, Leite...', en: 'E.g. Rice, Milk...', es: 'Ej: Arroz, Leche...' },
  category: { pt: 'Categoria', en: 'Category', es: 'Categoría' },
  unit: { pt: 'Unidade', en: 'Unit', es: 'Unidad' },
  quantity: { pt: 'Quantidade', en: 'Quantity', es: 'Cantidad' },
  minQuantity: { pt: 'Qtd. mínima', en: 'Min. quantity', es: 'Cant. mínima' },
  price: { pt: 'Valor', en: 'Price', es: 'Precio' },
  trialDaysLeft: { pt: 'restante do período de teste', en: 'left in trial period', es: 'restante del período de prueba' },
  trialDaysLeftPlural: { pt: 'restantes do período de teste', en: 'left in trial period', es: 'restantes del período de prueba' },
  premiumTitle: { pt: 'Premium', en: 'Premium', es: 'Premium' },
  premiumDesc: { pt: 'Acesso completo por', en: 'Full access for', es: 'Acceso completo por' },
  premiumSubscribe: { pt: 'Assinar Agora', en: 'Subscribe Now', es: 'Suscribirse Ahora' },
  day: { pt: 'dia', en: 'day', es: 'día' },
  dayPlural: { pt: 'dias', en: 'days', es: 'días' },
  subBannerTitle: { pt: 'Assinatura Necessária', en: 'Subscription Required', es: 'Suscripción Necesaria' },
  subBannerCancel: { pt: '30 dias para cancelar', en: '30 days to cancel', es: '30 días para cancelar' },
  cancelPolicyInfo: { pt: 'Você tem até 30 dias para cancelar a assinatura se desejar.', en: 'You have up to 30 days to cancel your subscription if you wish.', es: 'Tienes hasta 30 días para cancelar la suscripción si lo deseas.' },
  pricingDescFirstAccess: { pt: 'Para começar a usar o Magicmart AI, escolha um plano abaixo. O pagamento é necessário para o primeiro acesso.', en: 'To start using Magicmart AI, choose a plan below. Payment is required for first-time access.', es: 'Para comenzar a usar Magicmart AI, elija um plan. El pago es necesario para el primer acceso.' },
  subExpiryWarning: { pt: 'para a assinatura expirar. Renove agora!', en: 'until subscription expires. Renew now!', es: 'para que expire la suscripción. ¡Renueva ahora!' },
  trialExpiryWarning: { pt: 'restantes de teste. Assine para continuar!', en: 'left in trial. Subscribe to continue!', es: 'restantes de prueba. ¡Suscríbete para continuar!' },
  trialExpired: { pt: 'Período de Teste Encerrado', en: 'Trial Period Ended', es: 'Período de Prueba Terminado' },
  trialExpiredDesc: { pt: 'Seu período de 14 dias acabou. Assine para continuar organizando suas compras com IA.', en: 'Your 14-day trial has ended. Subscribe to continue organizing your shopping with AI.', es: 'Tu período de 14 días ha terminado. Suscríbete para continuar.' },
  pricingDescTrial: { pt: 'Aproveite o Magicmart AI. Assine agora para garantir acesso após o período de teste.', en: 'Enjoy Magicmart AI. Subscribe now to ensure access after the trial period.', es: 'Disfruta Magicmart AI. Suscríbete ahora para asegurar el acceso después de la prueba.' },
  loginToPayment: { pt: 'Por favor, faça login para realizar o pagamento.', en: 'Please log in to make a payment.', es: 'Por favor, inicia sesión para realizar el pago.' },
  paymentSuccess: { pt: 'Pagamento realizado com sucesso! Bem-vindo ao Premium.', en: 'Payment successful! Welcome to Premium.', es: '¡Pago realizado con éxito! Bienvenido a Premium.' },
  payment: { pt: 'Pagamento', en: 'Payment', es: 'Pago' },
  paymentDesc: { pt: 'Gerenciar assinatura', en: 'Manage subscription', es: 'Gestionar suscripción' },
  preparingCheckout: { pt: 'Preparando checkout...', en: 'Preparing checkout...', es: 'Preparando el pago...' },
  verifyingPayment: { pt: 'Verificando seu pagamento...', en: 'Verifying your payment...', es: 'Verificando su pago...' },
  redirectingToStripe: { pt: 'Redirecionando para o Stripe...', en: 'Redirecting to Stripe...', es: 'Redirigiendo a Stripe...' },
  stripeCheckoutInfo: { pt: 'Você será levado ao ambiente seguro do Stripe para concluir sua assinatura.', en: 'You will be taken to Stripe\'s secure environment to complete your subscription.', es: 'Se le llevará al entorno seguro de Stripe para completar su suscripción.' },
  renew: { pt: 'Renovar', en: 'Renew', es: 'Renovar' },
  refund: { pt: 'Reembolso', en: 'Refund', es: 'Reembolso' },
  renewDesc: { pt: 'Renovar assinatura anual', en: 'Renew annual subscription', es: 'Renovar suscripción anual' },
  refundDesc: { pt: 'Solicitar reembolso (até 30 dias)', en: 'Request refund (up to 30 days)', es: 'Solicitar reembolso (hasta 30 días)' },
  appTagline: { pt: 'Sua despensa inteligente e econômica', en: 'Your smart and cost-effective pantry', es: 'Tu despensa inteligente y económica' },
  appWillRestart: { pt: 'O app será reiniciado em instantes', en: 'The app will restart in moments', es: 'La app se reiniciará en instantes' },
  consumptionAnalysis: { pt: 'Análise de consumo', en: 'Consumption analysis', es: 'Análisis de consumo' },
  thisMonth: { pt: 'Este Mês', en: 'This Month', es: 'Este Mes' },
  avgPerMonth: { pt: 'Média/Mês', en: 'Avg/Month', es: 'Promedio/Mes' },
  marketVisits: { pt: 'Idas ao Mercado', en: 'Market Visits', es: 'Visitas al Mercado' },
  seeDetails: { pt: 'ver detalhes →', en: 'see details →', es: 'ver detalhes →' },
  estimatedInflation: { pt: 'Inflação Estimada', en: 'Estimated Inflation', es: 'Inflación Estimada' },
  monthlyEvolution: { pt: 'Evolução Mensal', en: 'Monthly Evolution', es: 'Evolución Mensal' },
  lastMonths: { pt: 'Últimos {count} meses', en: 'Last {count} months', es: 'Últimos {count} meses' },
  spending: { pt: 'Gasto', en: 'Spending', es: 'Gasto' },
  noEvolutionData: { pt: 'Sem dados de compras para exibir evolução mensal.', en: 'No shopping data to display monthly evolution.', es: 'Sin datos para mostrar evolución mensual.' },
  spendingByCategory: { pt: 'Gastos por Categoria', en: 'Spending by Category', es: 'Gastos por Categoría' },
  noCategoryData: { pt: 'Sem dados de categorias para exibir.', en: 'No category data to display.', es: 'Sin datos de categorías.' },
  mostPurchased: { pt: 'Mais Comprados', en: 'Most Purchased', es: 'Más Comprados' },
  noHistoryProducts: { pt: 'Sem produtos no histórico.', en: 'No products in history.', es: 'Sin productos en el historial.' },
  mostVisitedStores: { pt: 'Locais Mais Visitados', en: 'Most Visited Locations', es: 'Lugares Más Visitados' },
  visit: { pt: 'visita', en: 'visit', es: 'visita' },
  visits: { pt: 'visitas', en: 'visits', es: 'visitas' },
  openInMaps: { pt: 'Abrir no Google Maps', en: 'Open in Google Maps', es: 'Abrir en Google Maps' },
  noVisitsRecorded: { pt: 'Nenhuma visita registrada.', en: 'No visits recorded.', es: 'No hay visitas registradas.' },
  potentialSavings: { pt: 'Economia Potencial', en: 'Potential Savings', es: 'Ahorro Potencial' },
  moreHistoryNeeded: { pt: 'Necessário mais dados históricos', en: 'More history data needed', es: 'Se necesitan más datos históricos' },
  savingsDisclaimer: { pt: 'Valor estimado. A economia real depende de disponibilidade, localização e variações de preço.', en: 'Estimated value. Real savings depend on availability, location and price variations.', es: 'Valor estimado. El ahorro real depende de la disponibilidad, ubicación y variaciones de precio.' },
  cheapestDays: { pt: 'Dias Mais Baratos', en: 'Cheapest Days', es: 'Días Más Baratos' },
  savingsAnalysis: { pt: 'Análise de economia e gastos', en: 'Savings and spending analysis', es: 'Análisis de ahorro y gastos' },
  veryCheap: { pt: 'Muito barato', en: 'Very cheap', es: 'Muy barato' },
  cheap: { pt: 'Barato', en: 'Cheap', es: 'Barato' },
  veryExpensive: { pt: 'Muito caro', en: 'Very expensive', es: 'Muy caro' },
  expensive: { pt: 'Caro', en: 'Expensive', es: 'Caro' },
  weekDaysTitle: { pt: 'Dias da Semana', en: 'Week Days', es: 'Días de la Semana' },
  monthDaysTitle: { pt: 'Dias do Mês', en: 'Month Days', es: 'Días del Mes' },
  heatmapLegendWeek: { pt: 'Últimas 4 semanas · Toque para ver os locais', en: 'Last 4 weeks · Tap to see locations', es: 'Últimas 4 semanas · Toca para ver locales' },
  heatmapLegendMonth: { pt: 'Últimos 3 meses · Toque para ver os locais', en: 'Last 3 months · Tap to see locations', es: 'Últimos 3 meses · Toca para ver locales' },
  bestLocations: { pt: 'Melhores Locais para Comprar', en: 'Best Locations to Buy', es: 'Mejores Lugares para Comprar' },
  productsMonitored: { pt: '{count} produtos monitorados', en: '{count} products monitored', es: '{count} productos monitoreados' },
  suggestedCheapestDaysTitle: { pt: 'Sugestões de dias de compras\npara este mês', en: 'Shopping day suggestions\nfor this month', es: 'Sugerencias de días de compras\nfor este mes' },
  lastThreeMonthsHistory: { pt: 'Histórico dos últimos três meses', en: 'Last three months history', es: 'Historial de los últimos tres meses' },
  noPurchasesThisMonthTitle: { pt: 'Nenhuma compra este mês', en: 'No purchases this month', es: 'Sin compras este mes' },
  noPurchasesThisMonthDesc: { pt: 'Você ainda não registrou nenhuma compra para o mês atual. Seus relatórios e histórico serão atualizados assim que você escanear sua primeira nota.', en: 'You haven\'t recorded any purchases for the current month yet. Your reports and history will update as soon as you scan your first receipt.', es: 'Aún no has registrado ninguna compra para el mes actual. Tus informes e historial se actualizarán tan pronto como escanees tu primer recibo.' },
  heatmapInfoBanner: { 
    pt: 'A medida que você cadastrar mais notas fiscais, as sugestões do calendário se tornarão cada vez mais precisas para o seu perfil de consumo.', 
    en: 'As you register more receipts, the calendar suggestions will become increasingly precise for your consumption profile.',
    es: 'A medida que registres más facturas, as sugerencias del calendario se volverán cada vez más precisas para tu perfil de consumo.'
  },
  addedToShoppingList: { pt: 'adicionado à lista Lembrete de Compras', en: 'added to Shopping Reminders', es: 'agregado a Recordatorios de Compra' },
  calendarWeekCode: { pt: 'S', en: 'W', es: 'S' },
  savingsIndex: { pt: 'Índice Economia', en: 'Savings Index', es: 'Índice Ahorro' },
  insufficientHistory: { pt: 'Histórico insuficiente para calcular economia por local.', en: 'Insufficient history to calculate savings by location.', es: 'Historial insuficiente para calcular ahorro por lugar.' },
  savingsIndexLegend: { pt: '* O Índice de Economia compara os preços pagos com o menor preço já registrado. 100% indica os melhores preços.', en: '* The Savings Index compares prices paid with the lowest price recorded. 100% indicates best prices.', es: '* El Índice de Ahorro compara los precios pagados con el menor precio registrado. 100% indica mejores precios.' },
  bestDiscounts: { pt: 'Produtos com melhores descontos', en: 'Products with best discounts', es: 'Productos con mejores descuentos' },
  highestIncreases: { pt: 'Produtos com maiores aumentos', en: 'Products with highest increases', es: 'Productos con mayores aumentos' },
  from: { pt: 'De:', en: 'From:', es: 'De:' },
  to: { pt: 'Para:', en: 'To:', es: 'Para:' },
  noPriceDrops: { pt: 'Nenhuma queda de preço detectada recentemente.', en: 'No price drops detected recently.', es: 'No se detectaron caídas de precio recientemente.' },
  noIncreases: { pt: 'Nenhum aumento significativo detectado.', en: 'No significant increases detected.', es: 'No se detectaron aumentos significativos.' },
  locationsVisited: { pt: '{count} local(is) visitado(s)', en: '{count} location(s) visited', es: '{count} lugar(es) visitado(s)' },
  variationOf: { pt: 'Variação de {percent}%', en: 'Variation of {percent}%', es: 'Variación de {percent}%' },
  recentPurchase: { pt: 'Compra Recente', en: 'Recent Purchase', es: 'Compra Recente' },
  previousPurchase: { pt: 'Compra Anterior', en: 'Previous Purchase', es: 'Compra Anterior' },
  closeDetails: { pt: 'Fechar Detalhes', en: 'Close Details', es: 'Cerrar Detalles' },
  estimated: { pt: 'Estimado', en: 'Estimated', es: 'Estimado' },
  estimatedTotalLabel: { pt: 'Total estimado:', en: 'Estimated total:', es: 'Total estimado:' },
  sentViaApp: { pt: 'Enviado via Magicmart AI 🌿', en: 'Sent via Magicmart AI 🌿', es: 'Enviado vía Magicmart AI 🌿' },
  noActiveListsToShare: { pt: 'Nenhuma lista ativa para compartilhar.', en: 'No active lists to share.', es: 'No hay listas activas para compartir.' },
  selectListsToShare: { pt: 'Selecione as listas que deseja compartilhar:', en: 'Select the lists you want to share:', es: 'Selecciona las listas que deseas compartir:' },
  sendViaWhatsApp: { pt: 'Enviar via WhatsApp ({count})', en: 'Send via WhatsApp ({count})', es: 'Enviar vía WhatsApp ({count})' },
  howItWorks: { pt: 'Como funciona?', en: 'How it works?', es: '¿Cómo funciona?' },
  shoppingStep1: { pt: 'Adicione os itens comprados um a um;', en: 'Add purchased items one by one;', es: 'Añade los ítems comprados uno a uno;' },
  shoppingStep2: { pt: 'Insira os itens usando uma lista ativa, reconhecimento de imagem ou manualmente;', en: 'Insert items using an active list, image recognition or manually;', es: 'Inserta los ítems usando una lista activa, reconocimiento de imagen o manualmente;' },
  shoppingStep3: { pt: 'Ao encerrar as compras, os itens vão direto para o estoque;', en: 'When closing shopping, items go straight to stock;', es: 'Al terminar las compras, los ítems van directo al stock;' },
  shoppingStep4: { pt: 'Após concluir sua compra, vá em histórico e escaneie o cupom para atualizar os preços.', en: 'After finishing your purchase, go to history and scan the receipt to update prices.', es: 'Tras concluir tu compra, ve al historial y escanea el cupón para actualizar precios.' },
  shoppingTip: { pt: 'Ao invés de adicionar itens um a um, prefira usar somente o escâner de cupom logo após as compras. É mais rápido e automático.', en: 'Instead of adding items one by one, prefer to use only the receipt scanner right after shopping. It is faster and automatic.', es: 'En lugar de añadir ítems uno a uno, prefiere usar solo el escáner de cupones tras las compras. Es más rápido y automático.' },
  informMarketLocation: { pt: 'Informe o local de compras', en: 'Inform market location', es: 'Informa el lugar de compras' },
  noItemsAdded: { pt: 'Nenhum item adicionado', en: 'No items added', es: 'No se añadieron ítems' },
  itemsAddedToStock: { pt: '{count} itens adicionados ao estoque', en: '{count} items added to stock', es: '{count} ítems añadidos al stock' },
  cameraAccessError: { pt: 'Não foi possível acessar a câmera:', en: 'Could not access camera:', es: 'No se pudo acceder a la cámara:' },
  chooseRegisterMode: { pt: 'Escolha como registrar suas compras', en: 'Choose how to register your purchases', es: 'Elige cómo registrar tus compras' },
  withList: { pt: 'Com Lista', en: 'With List', es: 'Com Lista' },
  withListDesc: { pt: 'Abrir listas ativas para fazer compras', en: 'Open active lists to go shopping', es: 'Abrir listas activas para comprar' },
  registerAction: { pt: 'Registrar', en: 'Register', es: 'Registrar' },
  registerDesc: { pt: 'Usar câmera para reconhecer produtos', en: 'Use camera to recognize products', es: 'Usar cámara para reconocer productos' },
  byCategory: { pt: 'Por Categoria', en: 'By Category', es: 'Por Categoría' },
  byCategoryDesc: { pt: 'Buscar produto por categoria', en: 'Search product by category', es: 'Buscar producto por categoría' },
  registerPurchase: { pt: 'Registrar Compra', en: 'Register Purchase', es: 'Registrar Compra' },
  purchaseByCategory: { pt: 'Compra por Categoria', en: 'Purchase by Category', es: 'Compra por Categoría' },
  marketNameLabel: { pt: 'Nome do mercado', en: 'Market name', es: 'Nombre del mercado' },
  marketNamePlaceholder: { pt: 'Ex: Supermercado Extra', en: 'Ex: Walmart', es: 'Ej: Supermercado Central' },
  obtaining: { pt: 'Obtendo...', en: 'Obtaining...', es: 'Obteniendo...' },
  useLocation: { pt: 'Usar localização', en: 'Use location', es: 'Usar ubicación' },
  photoStepInstruction: { pt: 'Tire a foto do rótulo do produto que quer adicionar;', en: 'Take a photo of the product label you want to add;', es: 'Toma una foto de la etiqueta del producto que quieres añadir;' },
  manualStepInstruction: { pt: 'Adicione produtos manualmente a partir da lista de categorias;', en: 'Add products manually from the category list;', es: 'Añade productos manualmente desde la lista de categorías;' },
  pointToProduct: { pt: 'Aponte para o produto', en: 'Point to the product', es: 'Apunta al producto' },
  analyzingProduct: { pt: 'Analisando Produto', en: 'Analyzing Product', es: 'Analizando Producto' },
  aiIdentifyingItem: { pt: 'A Inteligência Artificial está identificando o item...', en: 'The AI is identifying the item...', es: 'La Inteligencia Artificial está identificando el ítem...' },
  mayTakeSeconds: { pt: 'Isso pode levar alguns segundos', en: 'This may take a few seconds', es: 'Esto puede tardar unos segundos' },
  shoppingInProgress: { pt: 'Compras em andamento', en: 'Shopping in progress', es: 'Compras en curso' },
  finishShopping: { pt: 'Encerrar Compras', en: 'Finish Shopping', es: 'Terminar Compras' },
  cancelShopping: { pt: 'Cancelar Compras', en: 'Cancel Shopping', es: 'Cancelar Compras' },
  developerModeDesc: { pt: 'Entrar direto no app para testes', en: 'Enter app directly for testing', es: 'Entrar directo para pruebas' },
  backup: { pt: 'Backup', en: 'Backup', es: 'Respaldo' },
  backupDesc: { pt: 'Gerenciar backups dos seus dados', en: 'Manage data backups', es: 'Gestionar copias de seguridad' },
  makeBackup: { pt: 'Fazer Backup', en: 'Make Backup', es: 'Hacer Copia' },
  restoreLastBackup: { pt: 'Restaurar último backup', en: 'Restore last backup', es: 'Restaurar última copia' },
  restoreFromFile: { pt: 'Restaurar com arquivo', en: 'Restore from file', es: 'Restaurar con archivo' },
  backupSuccess: { pt: 'Backup realizado com sucesso!', en: 'Backup successful!', es: 'Copia realizada con éxito!' },
  restoreSuccess: { pt: 'Dados restaurados com sucesso!', en: 'Data restored successfully!', es: '¡Datos restaurados con éxito!' },
  restoreError: { pt: 'Erro ao restaurar dados. Verifique o arquivo.', en: 'Error restoring data. Check the file.', es: 'Error al restaurar. Revisa el archivo.' },
  lastBackupFound: { pt: 'Último backup encontrado de:', en: 'Last backup found from:', es: 'Última copia encontrada de:' },
  noLastBackup: { pt: 'Nenhum backup local encontrado.', en: 'No local backup found.', es: 'No se encontró copia local.' },
  backupStatus: { pt: 'Status do Backup', en: 'Backup Status', es: 'Estado del Respaldo' },
  backupError: { pt: 'Erro ao realizar backup.', en: 'Error performing backup.', es: 'Error al realizar respaldo.' },
  saveOnDevice: { pt: 'Salvar dados no aparelho', en: 'Save data on device', es: 'Guardar datos en el dispositivo' },
  recoverLocalBackup: { pt: 'Recuperar backup local', en: 'Recover local backup', es: 'Recuperar respaldo local' },
  selectJsonFile: { pt: 'Selecionar arquivo .json', en: 'Select .json file', es: 'Selecionar archivo .json' },
  attention: { pt: 'Atenção', en: 'Attention', es: 'Atención' },
  backupWarning: { pt: 'Ao restaurar um backup, todos os dados atuais (estoque, listas e histórico) serão permanentemente substituídos pelos dados contidos no backup.', en: 'When restoring a backup, all current data (stock, lists and history) will be permanently replaced by the data in the backup.', es: 'Al restaurar un respaldo, todos los datos actuales serán reemplazados permanentemente por los datos del respaldo.' },
  restoringData: { pt: 'Restaurando dados...', en: 'Restoring data...', es: 'Restaurando datos...' },
  loadingApp: { pt: 'O app está carregando...', en: 'The app is loading...', es: 'La aplicación se está cargando...' },
  pricingDesc: { pt: 'Gerencie compras, estoque e gastos com inteligência artificial.', en: 'Manage shopping, stock and spending with artificial intelligence.', es: 'Gestiona compras, stock y gastos con inteligencia artificial.' },
  premiumPerYear: { pt: 'por ano', en: 'per year', es: 'por año' },
  processing: { pt: 'Processando...', en: 'Processing...', es: 'Procesando...' },
  pricingFeature1: { pt: 'Scanner de cupons com IA', en: 'AI receipt scanner', es: 'Escáner de recibos con IA' },
  pricingFeature2: { pt: 'Controle de estoque inteligente', en: 'Smart stock control', es: 'Control de stock inteligente' },
  pricingFeature3: { pt: 'Relatórios de economia', en: 'Savings reports', es: 'Informes de ahorro' },
  pricingFeature4: { pt: 'Listas de compras ilimitadas', en: 'Unlimited shopping lists', es: 'Listas de compras ilimitadas' },
  pricingFeature5: { pt: '30 dias para cancelar e reembolso', en: '30 days for cancellation and refund', es: '30 días para cancelar y reembolso' },
  critical: { pt: 'Crítico', en: 'Critical', es: 'Crítico' },
  low: { pt: 'Baixo', en: 'Low', es: 'Bajo' },
  ok: { pt: 'OK', en: 'OK', es: 'OK' },
  expired: { pt: 'Vencido', en: 'Expired', es: 'Vencido' },
  searchPlaceholder: { pt: 'Buscar por produto ou categoria...', en: 'Search for product or category...', es: 'Buscar por producto o categoría...' },
  swipeStockHint: { pt: '← Deslize para excluir · Deslize para adicionar ao lembrete →', en: '← Swipe to delete · Swipe to add to reminder →', es: '← Desliza para eliminar · Desliza para añadir recordatorio →' },
  edit: { pt: 'Editar', en: 'Edit', es: 'Editar' },
  purchased: { pt: 'comprado', en: 'purchased', es: 'comprado' },
  ago: { pt: 'atrás', en: 'ago', es: 'atrás' },
  daysRemaining: { pt: 'dias restantes', en: 'days remaining', es: 'días restantes' },
  learnedConsumption: { pt: 'Consumo aprendido', en: 'Learned consumption', es: 'Consumo aprendido' },
  purchases: { pt: 'compras', en: 'purchases', es: 'compras' },
  perCycle: { pt: 'por ciclo', en: 'per cycle', es: 'por ciclo' },
  zero: { pt: 'Zerar', en: 'Zero', es: 'Zerar' },
  productAddedToStock: { pt: 'Produto adicionado ao estoque!', en: 'Product added to stock!', es: '¡Producto añadido al stock!' },
  manualEntry: { pt: 'Entrada Manual', en: 'Manual Entry', es: 'Entrada Manual' },
  completed: { pt: 'Concluídas', en: 'Completed', es: 'Completadas' },
  archive: { pt: 'Arquivo', en: 'Archive', es: 'Archivo' },
  shoppingLists: { pt: 'Listas de Compras', en: 'Shopping Lists', es: 'Listas de Compras' },
  organizePurchases: { pt: 'Organize suas compras', en: 'Organize your purchases', es: 'Organiza tus compras' },
  swipeListHint: { pt: '← Deslize para excluir · Deslize para arquivar →', en: '← Swipe to delete · Swipe to archive →', es: '← Desliza para eliminar · Desliza para archivar →' },
  listNamePlaceholder: { pt: 'Nome da lista...', en: 'List name...', es: 'Nombre de la lista...' },
  noListsFound: { pt: 'Nenhuma lista encontrada', en: 'No lists found', es: 'No se encontraron listas' },
  inShopping: { pt: 'Em compras', en: 'Shopping', es: 'En compras' },
  listRestored: { pt: 'Lista restaurada.', en: 'List restored.', es: 'Lista restaurada.' },
  listDeleted: { pt: 'Lista excluída.', en: 'List deleted.', es: 'Lista eliminada.' },
  listArchived: { pt: 'Lista arquivada.', en: 'List archived.', es: 'Lista archivada.' },
  itemRemoved: { pt: 'Item removido', en: 'Item removed', es: 'Ítem eliminado' },
  alertRemoved: { pt: 'Alerta removido do estoque', en: 'Alert removed from stock', es: 'Alerta eliminado del stock' },
  finishShoppingPrompt: { pt: 'Ao clicar em Encerrar, os itens selecionados serão adicionados ao estoque', en: 'When clicking End, the selected items will be added to stock', es: 'Al hacer clic en Terminar, los ítems seleccionados se añadirán al stock' },
  shoppingEnded: { pt: 'Compras encerradas!', en: 'Shopping ended!', es: '¡Compras terminadas!' },
  selectAtLeastOne: { pt: 'Selecione ao menos um item', en: 'Select at least one item', es: 'Selecciona al menos un ítem' },
  locationObtained: { pt: 'Localização obtida com sucesso!', en: 'Location obtained successfully!', es: '¡Ubicación obtenida con éxito!' },
  coordsSaved: { pt: 'Localização salva como coordenadas.', en: 'Location saved as coordinates.', es: 'Ubicación guardada como coordenadas.' },
  locationError: { pt: 'Erro ao obter localização. Digite manualmente.', en: 'Error obtaining location. Enter manually.', es: 'Error al obtener ubicación. Escribe manualmente.' },
  enterLocation: { pt: 'Por favor, informe o local das compras.', en: 'Please enter the shopping location.', es: 'Por favor, informa el lugar de las compras.' },
  newItem: { pt: 'Novo Item', en: 'New Item', es: 'Nuevo Ítem' },
  add: { pt: 'Adicionar', en: 'Add', es: 'Añadir' },
  decline: { pt: 'Recusar', en: 'Decline', es: 'Rechazar' },
  accept: { pt: 'Aceitar', en: 'Accept', es: 'Aceptar' },
  recognizing: { pt: 'Reconhecendo...', en: 'Recognizing...', es: 'Reconociendo...' },
  openCamera: { pt: 'Abrir Câmera', en: 'Open Camera', es: 'Abrir Cámara' },
  continueBtn: { pt: 'Continuar', en: 'Continue', es: 'Continuar' },
  recognitionError: { pt: 'Erro ao reconhecer produto. Tente novamente.', en: 'Error recognizing product. Try again.', es: 'Error al reconocer el producto. Inténtalo de nuevo.' },
  permissionDenied: { pt: 'Permissão negada.', en: 'Permission denied.', es: 'Permiso denegado.' },
  itemsAddedRemaining: { pt: '{count} itens adicionados ao estoque. {remaining} itens permanecem na lista.', en: '{count} items added to stock. {remaining} items remain on list.', es: '{count} ítems añadidos al stock. {remaining} ítems permanecen en la lista.' },
  selected: { pt: 'selecionados', en: 'selected', es: 'seleccionados' },
  emptyList: { pt: 'Lista vazia. Adicione itens acima.', en: 'Empty list. Add items above.', es: 'Lista vacía. Añade ítems arriba.' },
  shoppingLocation: { pt: 'Local de Compras', en: 'Shopping Location', es: 'Local de Compras' },
  generalClassification: { pt: 'Classificação Geral', en: 'General Classification', es: 'Clasificación General' },
  supermarket: { pt: 'Supermercado', en: 'Market & Groceries', es: 'Supermercado' },
  restaurant: { pt: 'Bares e Restaurantes', en: 'Dining & Drinks', es: 'Bares y Restaurantes' },
  transport: { pt: 'Transporte e Apps', en: 'Transport & Fuel', es: 'Transporte y Apps' },
  maintenance: { pt: 'Casa e Manutenção', en: 'Home & Maintenance', es: 'Hogar y Mantenimiento' },
  categoryUpdated: { pt: 'Categoria atualizada!', en: 'Category updated!', es: '¡Categoria actualizada!' },
  transportMonthly: { pt: 'Gastos Mensais com Transporte', en: 'Monthly Transport Expenses', es: 'Gastos Mensuales con Transporte' },
  restaurantsMonthly: { pt: 'Gastos Mensais com Restaurante', en: 'Monthly Restaurant Expenses', es: 'Gastos Mensuales con Restaurante' },
  maintenanceYearly: { pt: 'Gastos Anuais com Manutenção da Casa', en: 'Yearly Maintenance Expenses', es: 'Gastos Anuales con Mantenimiento' },
  geminiLimitTitle: { pt: 'Limite Diário da IA', en: 'AI Daily Limit', es: 'Límite Diario de IA' },
  geminiLimitDesc: { pt: 'A sua chave API gratuita do Gemini possui um limite de requisições por minuto e por dia definido pelo Google. Se o scanner falhar, tente novamente em instantes ou amanhã.', en: 'Your free Gemini API key has a request limit per minute and per day set by Google. If the scanner fails, try again in a few moments or tomorrow.', es: 'Su clave API gratuita de Gemini tiene un límite de solicitudes por minuto y por día establecido por Google. Si el escáner falla, intente de nuevo en unos momentos o mañana.' },
  wherePurchased: { pt: 'Informe onde você fez as compras:', en: 'Enter where you made the purchases:', es: 'Informa dónde hiciste las compras:' },
  storePlaceholder: { pt: 'Ex: Supermercado Extra', en: 'e.g. Supermarket', es: 'Ej: Supermercado' },
  gettingAddress: { pt: 'Obtendo endereço...', en: 'Getting address...', es: 'Obteniendo dirección...' },
  useMyLocation: { pt: 'Usar minha localização', en: 'Use my location', es: 'Usar mi ubicación' },
  general: { pt: 'Geral', en: 'General', es: 'General' },
  digitalizeReceipts: { pt: 'Digitalize seus cupons fiscais', en: 'Digitize your receipts', es: 'Digitaliza tus recibos' },
  unnamedProduct: { pt: 'Produto sem nome', en: 'Unnamed product', es: 'Producto sin nombre' },
  unknownMarket: { pt: 'Mercado Desconhecido', en: 'Unknown Market', es: 'Mercado Desconocido' },
  newProduct: { pt: 'Novo Produto', en: 'New Product', es: 'Nuevo Producto' },
  un: { pt: 'un', en: 'un', es: 'un' },
  kg: { pt: 'kg', en: 'kg', es: 'kg' },
  g: { pt: 'g', en: 'g', es: 'g' },
  L: { pt: 'L', en: 'L', es: 'L' },
  ml: { pt: 'ml', en: 'ml', es: 'ml' },
  pct: { pt: 'pct', en: 'pack', es: 'paq' },
  cx: { pt: 'cx', en: 'box', es: 'caja' },
  dairy: { pt: 'Laticínios', en: 'Dairy', es: 'Lácteos' },
  grains: { pt: 'Grãos', en: 'Grains', es: 'Granos' },
  beverages: { pt: 'Bebidas', en: 'Beverages', es: 'Bebidas' },
  spices: { pt: 'Temperos', en: 'Spices', es: 'Especias' },
  cleaning: { pt: 'Limpeza', en: 'Cleaning', es: 'Limpieza' },
  meats: { pt: 'Carnes', en: 'Meats', es: 'Carnes' },
  fruits: { pt: 'Frutas', en: 'Fruits', es: 'Frutas' },
  food: { pt: 'Alimentos', en: 'Food', es: 'Alimentos' },
  hygiene: { pt: 'Higiene', en: 'Hygiene', es: 'Higiene' },
  produce: { pt: 'Hortifruti', en: 'Produce', es: 'Hortifruti' },
  bakery: { pt: 'Padaria', en: 'Bakery', es: 'Panadería' },
  others: { pt: 'Outros', en: 'Others', es: 'Otros' },
  'Laticínios': { pt: 'Laticínios', en: 'Dairy', es: 'Lácteos' },
  'Grãos': { pt: 'Grãos', en: 'Grains', es: 'Granos' },
  'Bebidas': { pt: 'Bebidas', en: 'Beverages', es: 'Bebidas' },
  'Temperos': { pt: 'Temperos', en: 'Spices', es: 'Especias' },
  'Limpeza': { pt: 'Limpeza', en: 'Cleaning', es: 'Limpieza' },
  'Carnes': { pt: 'Carnes', en: 'Meats', es: 'Carnes' },
  'Frutas': { pt: 'Frutas', en: 'Fruits', es: 'Frutas' },
  'Alimentos': { pt: 'Alimentos', en: 'Food', es: 'Alimentos' },
  'Higiene': { pt: 'Higiene', en: 'Higiene', es: 'Higiene' },
  'Hortifruti': { pt: 'Hortifruti', en: 'Produce', es: 'Hortifruti' },
  'Padaria': { pt: 'Padaria', en: 'Bakery', es: 'Panadería' },
  'Manutenção': { pt: 'Manutenção', en: 'Maintenance', es: 'Mantenimiento' },
  'Restaurante': { pt: 'Restaurante', en: 'Restaurant', es: 'Restaurante' },
  'Transporte': { pt: 'Transporte', en: 'Transport', es: 'Transporte' },
  'Outros': { pt: 'Outros', en: 'Others', es: 'Otros' },
  disableDevMode: { pt: 'Desativar Modo Desenvolvedor', en: 'Disable Developer Mode', es: 'Desactivar Modo Desarrollador' },
  backToNormalAuth: { pt: 'Voltar para autenticação normal', en: 'Back to normal authentication', es: 'Volver a autenticación normal' },
  devModeDisabled: { pt: 'Modo Desenvolvedor desativado', en: 'Developer Mode disabled', es: 'Modo Desarrollador desactivado' },
  clipboardError: { pt: 'Não foi possível acessar a área de transferência.', en: 'Could not access clipboard.', es: 'No se pudo acceder al portapapeles.' },
  import: { pt: 'Importar', en: 'Import', es: 'Importar' },
  export: { pt: 'Exportar', en: 'Export', es: 'Exportar' },
  importSuccess: { pt: 'itens importados com sucesso.', en: 'items imported successfully.', es: 'ítems importados con éxito.' },
  exportSuccess: { pt: 'itens exportados com sucesso.', en: 'items exported successfully.', es: 'ítems exportados con éxito.' },
  importError: { pt: 'Erro ao importar dados.', en: 'Error importing data.', es: 'Error al importar datos.' },
  exportError: { pt: 'Erro ao exportar dados.', en: 'Error exporting data.', es: 'Error al exportar datos.' },
  noDataFound: { pt: 'Nenhum dado encontrado.', en: 'No data found.', es: 'No se encontraron datos.' },
  invalidFile: { pt: 'Arquivo inválido.', en: 'Invalid file.', es: 'Archivo inválido.' },
  duplicatesIgnored: { pt: 'duplicados ignorados', en: 'duplicates ignored', es: 'duplicados ignorados' },
  allDataExists: { pt: 'Todos os itens já existem no histórico.', en: 'All items already exist in history.', es: 'Todos los ítems ya existen en el historial.' },
  csvFormatError: { pt: 'Erro no formato do arquivo CSV.', en: 'Error in CSV file format.', es: 'Error en el formato CSV.' },
  addImportedToStockQuestion: { pt: 'Deseja adicionar os itens importados ao estoque?', en: 'Do you want to add the imported items to stock?', es: '¿Deseas añadir los artículos importados al stock?' },
  addImportedToStockTitle: { pt: 'Atualizar Estoque', en: 'Update Stock', es: 'Actualizar Stock' },
  exportHistoryTitle: { pt: 'Exportar Histórico (CSV)', en: 'Export History (CSV)', es: 'Exportar Historial (CSV)' },
  exportAll: { pt: 'Exportar tudo', en: 'Export all', es: 'Exportar todo' },
  startDate: { pt: 'Data de Início', en: 'Start Date', es: 'Fecha de Inicio' },
  endDate: { pt: 'Data de Fim', en: 'End Date', es: 'Fecha de Fin' },
  exportHint: { pt: 'O arquivo exportado pode ser aberto no Excel, Google Sheets ou importado de volta.', en: 'The exported file can be opened in Excel, Google Sheets or imported back.', es: 'El archivo exportado se puede abrir en Excel, Google Sheets o importar de nuevo.' },
  scannerApiKeyWarning: { pt: 'Algo está errado com sua chave API Gemini.', en: 'Something is wrong with your Gemini API key.', es: 'Algo está mal con tu clave API Gemini.' },
  errorNewPhoto: { pt: 'Houve um problema na análise. Por favor, tire outra foto com melhor foco e enquadrando todos os itens.', en: 'There was a problem with the analysis. Please take another photo with better focus and framing all items.', es: 'Hubo un problema con el análisis. Por favor, toma otra foto con mejor enfoque y enmarcando todos los ítems.' },
  analyzingWait: { pt: 'Analisando... Aguarde.', en: 'Analyzing... Wait.', es: 'Analizando... Espere.' },
  reanalyzeBtn: { pt: 'Reanalisar', en: 'Reanalyze', es: 'Reanalizar' },
  confirmDateTitle: { pt: 'Confirmar Data', en: 'Confirm Date', es: 'Confirmar Fecha' },
  confirmDateDesc: { pt: 'Confirme a data da compra antes de salvar no histórico.', en: 'Confirm the purchase date before saving to history.', es: 'Confirma la fecha de compra antes de guardar en el historial.' },
  averagePurchase: { pt: 'Esta compra esteve na média das anteriores.', en: 'This purchase was in line with previous ones.', es: 'Esta compra estuvo en el promedio de las anteriores.' },
  priceHistoryTitle: { pt: 'Histórico de Preços', en: 'Price History', es: 'Historial de Precios' },
  priceHistoryDesc: { pt: 'Veja a variação de preços e locais de compra para este item.', en: 'See price variations and purchase locations for this item.', es: 'Variación de precios y lugares de compra.' },
  noHistoryFound: { pt: 'Nenhum histórico encontrado para este item.', en: 'No history found for this item.', es: 'Sin historial para este ítem.' },
  activeListsBanner: { 
    pt: 'Navegue e crie listas de compras com estimativas de preços. Saiba o valor da compra antes de fazer mercado.', 
    en: 'Browse and create shopping lists with price estimates. Know the purchase value before going to the market.', 
    es: 'Navegue y cree listas de compras con estimaciones de precios. Conozca el valor de la compra antes de ir al mercado.' 
  },
  alertsBanner: { 
    pt: 'Deslize os itens da lista de alertas para adicioná-los na lista de Lembrete de Compras. Nunca mais esqueça oque comprar.', 
    en: 'Swipe alert list items to add them to the Shopping Reminder list. Never forget what to buy again.', 
    es: 'Deslice los elementos de la lista de alertas para agregarlos a la lista de Recordatorios de Compra. No olvide nunca más qué comprar.' 
  },
  apiKeySaved: { pt: 'Chave API salva!', en: 'API Key saved!', es: 'Clave API guardada!' },
  apiKeyRemoved: { pt: 'Chave API removida.', en: 'API Key removed.', es: 'Clave API eliminada.' },
  enterKeyBeforeTest: { pt: 'Insira a chave antes de testar.', en: 'Enter key before testing.', es: 'Ingresa la clave antes de probar.' },
  testingConnection: { pt: 'testando conexão...', en: 'testing connection...', es: 'probando conexão...' },
  connectionSuccess: { pt: 'Conexão OK: ', en: 'Connection OK: ', es: 'Conexión OK: ' },
  developerMode: { pt: 'Modo Desenvolvedor', en: 'Developer Mode', es: 'Modo Desarrollador' },
  diagnosticTools: { pt: 'Ferramentas de Diagnóstico', en: 'Diagnostic Tools', es: 'Herramientas de Diagnóstico' },
  geminiConfig: { pt: 'Configuração Gemini', en: 'Gemini Configuration', es: 'Configuración Gemini' },
  yourApiKey: { pt: 'Sua Chave API', en: 'Your API Key', es: 'Tu Clave API' },
  clearKey: { pt: 'Limpar Chave', en: 'Clear Key', es: 'Limpar Clave' },
  getApiKeyAt: { pt: 'Obtenha em', en: 'Get at', es: 'Obtenla en' },
  saveKey: { pt: 'Salvar Chave', en: 'Save Key', es: 'Guardar Clave' },
  testActions: { pt: 'Ações de Teste', en: 'Test Actions', es: 'Acciones de Prueba' },
  testIaConnection: { pt: 'Testar IA', en: 'Test AI', es: 'Probar IA' },
  diagnosticResult: { pt: 'Resultado do Diagnóstico', en: 'Diagnostic Result', es: 'Resultado del Diagnóstico' },
  devModeWarning: { pt: 'Atenção: Estas ferramentas são para uso técnico.', en: 'Warning: These tools are for technical use.', es: 'Atención: Estas ferramentas são para uso técnico.' },
  versioning: { pt: 'Versão do App', en: 'App Version', es: 'Versión de la App' },
  currentVersion: { pt: 'Versão Atual', en: 'Current Version', es: 'Versión Actual' },
  lastDeploy: { pt: 'Último Deploy', en: 'Last Deploy', es: 'Último Deploy' },
  versionWarning: { pt: 'Mantenha o app atualizado para melhores resultados.', en: 'Keep the app updated for best results.', es: 'Mantén la app actualizada para mejores resultados.' },
  statusContext: { pt: 'Status da conta:', en: 'Account status:', es: 'Estado de la cuenta:' },
  emptyListText: { pt: 'Sua lista está vazia.', en: 'Your list is empty.', es: 'Tu lista está vacía.' },
  basePrice: { pt: 'Preço Base', en: 'Base Price', es: 'Precio Base' },
  errorOpeningPortal: { pt: 'Erro ao abrir o portal de assinatura', en: 'Error opening subscription portal', es: 'Error al abrir el portal de suscripción' },
  errorOpeningCheckout: { pt: 'Erro ao abrir o checkout', en: 'Error opening checkout', es: 'Error al abrir el pago' },
  loginError: { pt: 'Erro ao entrar. Verifique suas credenciais.', en: 'Login error. Check your credentials.', es: 'Error al entrar. Revisa tus credenciales.' },
  popupBlockedError: { pt: 'Popup bloqueado. Por favor, permita popups para fazer login.', en: 'Popup blocked. Please allow popups to sign in.', es: 'Popup bloqueado. Por favor permite popups para iniciar sesión.' },
};

function formatNumber(value: number, lang: Lang): string {
  const locale = lang === 'en' ? 'en-US' : lang === 'es' ? 'es-ES' : 'pt-BR';
  return value.toLocaleString(locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  currency: string;
  formatCurrency: (value: number) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'pt',
  setLang: () => {},
  t: (k) => k,
  currency: 'R$',
  formatCurrency: (v) => `R$ ${v.toFixed(2)}`,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() =>
    (localStorage.getItem('app-lang') as Lang) || 'pt'
  );
  const [isEurope, setIsEurope] = useState<boolean>(() => {
    return localStorage.getItem('app-region') === 'europe';
  });

  // Region detection removed to follow "Just-in-Time" permissions guidelines
  useEffect(() => {
    // We no longer automatically request geolocation on startup.
    // If needed in the future, we should add a manual setting for the user.
    const cached = localStorage.getItem('app-region');
    if (!cached) {
      localStorage.setItem('app-region', 'other');
    }
  }, []);

  const setLang = (l: Lang) => {
    localStorage.setItem('app-lang', l);
    setLangState(l);
  };

  const t = (key: string) => translations[key]?.[lang] || key;

  // Currency: pt/es in Europe → €, otherwise default by lang
  const currency = (lang === 'pt' || lang === 'es') && isEurope ? '€' : currencyByLang[lang];

  const fc = (value: number) => `${currency} ${formatNumber(value, lang)}`;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, currency, formatCurrency: fc }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
